from django.urls import path

from savings_bank.views import (
    AccountBalanceView,
    AccountCreateView,
    AccountDetailsView,
    AccountListView,
    DepositView,
    LoginView,
    LogoutView,
    TransactionView,
    TransferView,
    UserCreateView,
    WithdrawalView,
)

urlpatterns = [
    path(
        route="auth/login/",
        view=LoginView.as_view(),
        name="login_api",
    ),
    path(
        route="auth/logout/",
        view=LogoutView.as_view(),
        name="logout_api",
    ),
    path(
        route="users/",
        view=UserCreateView.as_view(),
        name="user_api",
    ),
    path(
        route="accounts/all/",
        view=AccountListView.as_view(),
        name="accounts_api",
    ),
    path(
        route="accounts/<int:account_id>/balance/",
        view=AccountBalanceView.as_view(),
        name="account_balance_api",
    ),
    path(
        route="accounts/",
        view=AccountCreateView.as_view(),
        name="account_api",
    ),
    path(
        route="accounts/<int:account_id>/",
        view=AccountDetailsView.as_view(),
        name="account_api",
    ),
    path(
        route="transactions/deposit/",
        view=DepositView.as_view(),
        name="deposit_api",
    ),
    path(
        route="transactions/withdraw/",
        view=WithdrawalView.as_view(),
        name="withdrawal_api",
    ),
    path(
        route="transactions/transfer/",
        view=TransferView.as_view(),
        name="transfer_api",
    ),
    path(
        route="transactions/<int:account_id>/",
        view=TransactionView.as_view(),
        name="transaction_api",
    ),
]
